name: Test on PR with Maven

on:
  pull_request:
    branches: [ "master" ]

jobs:
  mvn-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Test with Maven
      run: mvn test
